In [17]:
import pandas as pd
import numpy as np

In [18]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [19]:
df = pd.read_csv("covid_toy.csv")
df.sample(5)

    age  gender  fever   cough     city has_covid
72   83  Female  101.0    Mild  Kolkata        No
75    5    Male  102.0    Mild  Kolkata       Yes
50   19    Male  101.0    Mild    Delhi       Yes
25   23    Male    NaN    Mild   Mumbai        No
17   40  Female   98.0  Strong    Delhi        No

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.drop("has_covid", axis=1), df["has_covid"], test_size=0.2)

In [21]:
# Hectic Way

# Simple Imputer
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[["fever"]])
X_test_fever = si.fit_transform(X_test[["fever"]])

X_train_fever.shape

(80, 1)

In [32]:
# Ordinal Encoding

oe = OrdinalEncoder(categories=[["Mild", "Strong"]])

X_train_cough = oe.fit_transform(X_train[["cough"]])
X_test_cough = oe.fit_transform(X_test[["cough"]])

X_train_cough

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.]])

In [31]:
# One Hot Encoding

ohe = OneHotEncoder(drop="first")

X_train_gender_city = ohe.fit_transform(X_train[["gender", "city"]])
X_test__gender_city = ohe.fit_transform(X_test[["gender", "city"]])

X_train_gender_city

<80x4 sparse matrix of type '<class 'numpy.float64'>'
	with 94 stored elements in Compressed Sparse Row format>

In [33]:
# Extracting Age

X_train_age = X_train.drop(columns=["gender", "city", "fever", "cough"]).values
X_test_age = X_test.drop(columns=["gender", "city", "fever", "cough"]).values

X_train_age

array([[14],
       [81],
       [14],
       [20],
       [ 6],
       [ 5],
       [49],
       [10],
       [71],
       [20],
       [34],
       [49],
       [82],
       [51],
       [26],
       [22],
       [65],
       [64],
       [18],
       [65],
       [79],
       [47],
       [ 8],
       [19],
       [64],
       [13],
       [56],
       [27],
       [49],
       [27],
       [24],
       [72],
       [24],
       [81],
       [69],
       [83],
       [11],
       [ 5],
       [34],
       [70],
       [10],
       [68],
       [55],
       [20],
       [19],
       [82],
       [83],
       [25],
       [38],
       [48],
       [23],
       [74],
       [65],
       [42],
       [34],
       [25],
       [ 5],
       [71],
       [75],
       [12],
       [60],
       [73],
       [27],
       [54],
       [51],
       [19],
       [46],
       [38],
       [80],
       [60],
       [42],
       [64],
       [51],
       [73],
       [80],
       [65],
       [17],
       [34],
       [83],
       [16]])

In [25]:
# Using Column Transformer
from sklearn.compose import ColumnTransformer
transformer = ColumnTransformer(transformers=[
    ("tnf1", SimpleImputer(), ["fever"]), 
    ("tnf2", OrdinalEncoder(categories=[["Mild", "Strong"]]), ["cough"]),
    ("tnf3", OneHotEncoder(drop="first"), ["gender", "city"])
], remainder="passthrough")

In [34]:
transformer.fit_transform(X_train)

array([[ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  14.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  81.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  14.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  20.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   6.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,   5.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  49.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  10.       ],
       [100.8028169,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [100.8028169,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  20.       ],
       [100.8028169,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  34.       ],
       [102.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [100.8028169,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [101.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  51.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  26.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  22.       ],
       [ 99.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  65.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  64.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  18.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  65.       ],
       [100.8028169,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  79.       ],
       [101.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  47.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   8.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  19.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  64.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  13.       ],
       [104.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  56.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  27.       ],
       [101.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  49.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  24.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  72.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  24.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  81.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  69.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [100.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  11.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   0.       ,
          1.       ,   5.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  34.       ],
       [103.       ,   1.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  70.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  10.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  68.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  55.       ],
       [102.       ,   1.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  20.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  19.       ],
       [102.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  82.       ],
       [ 98.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  83.       ],
       [ 99.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  25.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  38.       ],
       [103.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  48.       ],
       [100.8028169,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  23.       ],
       [102.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          1.       ,  74.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  65.       ],
       [101.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  42.       ],
       [104.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  34.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  25.       ],
       [100.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,   5.       ],
       [ 98.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  71.       ],
       [100.8028169,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  75.       ],
       [ 98.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  12.       ],
       [103.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  60.       ],
       [103.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  73.       ],
       [100.       ,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  27.       ],
       [104.       ,   1.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  54.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  51.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  19.       ],
       [103.       ,   1.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  46.       ],
       [100.8028169,   0.       ,   1.       ,   1.       ,   0.       ,
          0.       ,  38.       ],
       [100.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  80.       ],
       [ 99.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          1.       ,  60.       ],
       [100.8028169,   1.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  42.       ],
       [ 98.       ,   0.       ,   0.       ,   0.       ,   0.       ,
          0.       ,  64.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  51.       ],
       [ 98.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  73.       ],
       [ 98.       ,   0.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  80.       ],
       [ 99.       ,   0.       ,   1.       ,   0.       ,   0.       ,
          0.       ,  65.       ],
       [104.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  17.       ],
       [101.       ,   1.       ,   0.       ,   1.       ,   0.       ,
          0.       ,  34.       ],
       [101.       ,   0.       ,   0.       ,   0.       ,   1.       ,
          0.       ,  83.       ],
       [104.       ,   0.       ,   1.       ,   0.       ,   1.       ,
          0.       ,  16.       ]])

In [27]:
flats = transformer.named_transformers_["tnf3"].get_feature_names_out(
    ["gender", "city"]
)

In [28]:
vals = transformer.transform(X_train)
vals.shape
", ".join(flats)

'gender_Male, city_Delhi, city_Kolkata, city_Mumbai'

In [29]:
df = pd.DataFrame(vals, columns=["fever", "cough",  *flats, "age"],)
# ["fever", "cough", ", ".join(flats), "age"]

In [30]:
df

    fever  cough  gender_Male  city_Delhi  city_Kolkata  city_Mumbai   age
0    99.0    0.0          0.0         0.0           0.0          1.0  14.0
1   101.0    0.0          0.0         0.0           0.0          1.0  81.0
2   101.0    1.0          1.0         0.0           0.0          0.0  14.0
3   101.0    0.0          0.0         0.0           0.0          0.0  20.0
4   104.0    0.0          0.0         0.0           1.0          0.0   6.0
..    ...    ...          ...         ...           ...          ...   ...
75   99.0    0.0          1.0         0.0           0.0          0.0  65.0
76  104.0    0.0          0.0         0.0           1.0          0.0  17.0
77  101.0    1.0          0.0         1.0           0.0          0.0  34.0
78  101.0    0.0          0.0         0.0           1.0          0.0  83.0
79  104.0    0.0          1.0         0.0           1.0          0.0  16.0

[80 rows x 7 columns]